// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:bs_flutter/app/models/bill.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BillAdapter());
    registerAdapter(BillItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BillAdapter());
    registerAdapter(BillItemAdapter());
  }
}
